# Generated by Django 2.1.5 on 2019-04-13 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_app', '0002_comment_question_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='comment_content',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='commented_by',
        ),
    ]
