# Generated by Django 2.1.5 on 2019-04-13 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_app', '0003_auto_20190413_0639'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_content',
            field=models.TextField(default=1, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='commented_by',
            field=models.TextField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
