# Generated by Django 2.1.5 on 2019-04-13 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest_app', '0004_auto_20190413_0642'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote', models.IntegerField()),
                ('answer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_app.Answer')),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_app.Question')),
            ],
        ),
    ]
