# Generated by Django 2.1.5 on 2019-04-13 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_app', '0005_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='increase',
            field=models.BooleanField(default=True),
        ),
    ]
