# Generated by Django 2.1.5 on 2019-04-13 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_app', '0006_vote_increase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='id',
        ),
        migrations.AddField(
            model_name='vote',
            name='vote_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
